/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myproject;

import controller.ProjectController;
import controller.TaskController;
import java.util.List;
import model.Project;
import model.Task;


public class App {

    public static void main(String[] args) throws Exception {
        
//        ProjectController controller = new ProjectController();
//        Project project = new Project();
//        
//        project.setName("PROJETO UM");
//        project.setDescription("PRIMEIRO TESTE");
//        controller.save(project);       
//        
//        project.setId(1);
//        project.setName("NOVO NOME");
//        controller.update(project);

//        List<Project> projects = controller.getAll();
//        System.out.println("Total de Projetos: " + projects.size());
//        
//       controller.removeById(2);

//        TaskController controller = new TaskController();
//        Task task = new Task();
//        
////        task.setName("TAREFA UM");
////        task.setDescription("PRIMEIRO TESTE");
//        task.setIdProjects(2);
////        controller.save(task);      
//
//          task.setIdTasks(1);
//          task.setName("ATUALIZANDO");
//          controller.update(task);
//          
//          List<Task> tasks = controller.getAll(2);
//          System.out.println("Total de Projetos: " + tasks.size());
//        
//          controller.removeById(1);
        
    }
}
